# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apis/poi/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ACRNAME: 'openhackt259mvo0acr.azurecr.io'
  BASEIMAGETAG: 'v1' 

steps:
- script: dotnet build apis/poi/poi.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj
  displayName: 'dotnet test'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'OTA-PRD-447(5f20e20f-aa5b-4aef-b6a0-6a17499fad01)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile'
    workingDirectory: 'apis/poi/web'
